"""
AI-assisted threat modeling.

Instead of hand-declaring the threat profile, an LLM proposes the ATT&CK / ATLAS
techniques a given system is exposed to ("a web app behind a WAF" -> credential
stuffing, SQLi, scanning, DoS, command injection, LLM prompt injection, ...).
We then mark each technique COVERED (a detector exists) or a GAP.

- "What threats are we exposed to?"  -> generated by the LLM (the threat profile)
- "Which do we actually detect?"     -> derived automatically from DETECTED_TECHNIQUES
- "Where are the gaps?"              -> the rest

The profile is generated once (CLI: `threatsight threat-model`) and cached to
data/threat_model.json; the dashboard reads the cache (no LLM call per request).
Falls back to a built-in profile if there's no cache / no API key, so the
dashboard always works.
"""

from __future__ import annotations

import json
from pathlib import Path

from pydantic import BaseModel, Field

from ..investigation.ai_analyze import DEFAULT_MODEL, _make_client

CACHE = Path("data/threat_model.json")

# The detector registry: techniques our detectors actually cover.
# (Add the technique id here when you add a detector for it.)
DETECTED_TECHNIQUES = {"T1110.004", "T1190", "T1595.002", "AML.T0051"}

# Used when there's no cached model / no API key, so things always work.
FALLBACK_PROFILE = [
    {"framework": "ATT&CK", "technique": "T1110.004", "name": "Credential Stuffing", "tactic": "Credential Access"},
    {"framework": "ATT&CK", "technique": "T1190", "name": "Exploit Public-Facing Application", "tactic": "Initial Access"},
    {"framework": "ATT&CK", "technique": "T1595.002", "name": "Vulnerability Scanning", "tactic": "Reconnaissance"},
    {"framework": "ATT&CK", "technique": "T1499", "name": "Endpoint Denial of Service", "tactic": "Impact"},
    {"framework": "ATT&CK", "technique": "T1059", "name": "Command and Scripting Interpreter", "tactic": "Execution"},
    {"framework": "ATLAS", "technique": "AML.T0051", "name": "LLM Prompt Injection", "tactic": "LLM Initial Access"},
]


class ThreatTechnique(BaseModel):
    framework: str = Field(description="ATT&CK or ATLAS")
    technique: str = Field(description="technique id, e.g. T1190 or AML.T0051")
    name: str
    tactic: str


class ThreatProfile(BaseModel):
    techniques: list[ThreatTechnique]


SYSTEM = (
    "You are a threat-modeling assistant. Given a system description, list the MITRE ATT&CK "
    "techniques (and MITRE ATLAS techniques for any AI/LLM exposure) the system is realistically "
    "exposed to. Return the 6-12 most relevant. Use the report_threat_profile tool."
)


def generate_threat_model(system: str, model: str = DEFAULT_MODEL) -> list[dict]:
    """Ask the LLM to propose the threat profile for a system description."""
    client = _make_client()
    tool = {
        "name": "report_threat_profile",
        "description": "Report the threat profile (relevant ATT&CK/ATLAS techniques).",
        "input_schema": ThreatProfile.model_json_schema(),
    }
    resp = client.messages.create(
        model=model, max_tokens=1500, system=SYSTEM, tools=[tool],
        tool_choice={"type": "tool", "name": "report_threat_profile"},
        messages=[{"role": "user", "content": f"System: {system}"}],
    )
    for b in resp.content:
        if b.type == "tool_use":
            return ThreatProfile.model_validate(b.input).model_dump()["techniques"]
    return []


def save_threat_model(rows: list[dict], path=CACHE) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(json.dumps(rows, indent=2), encoding="utf-8")


def load_threat_model(path=CACHE) -> list[dict]:
    p = Path(path)
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else list(FALLBACK_PROFILE)


def coverage(detected_ids=None, threat_rows=None) -> list[dict]:
    """Annotate each threat: covered (a detector exists) vs gap, and observed this run."""
    rows = threat_rows if threat_rows is not None else load_threat_model()
    detected = set(detected_ids or [])
    out = []
    for t in rows:
        covered = t["technique"] in DETECTED_TECHNIQUES
        out.append({
            **t,
            "covered": covered,
            "observed": t["technique"] in detected,
            "status": "covered" if covered else "gap",
        })
    return out


def summary(rows: list[dict]) -> dict:
    return {
        "total": len(rows),
        "covered": sum(r["covered"] for r in rows),
        "gaps": sum(not r["covered"] for r in rows),
        "observed": sum(r["observed"] for r in rows),
    }